"""授权书六字段校验 + 审计哈希链的测试。

对应规范 `authorization.md` 的验收单：
- 授权书**六个字段齐全**（缺一个就是不合格设计）
- 审计哈希链能验（改一条能验出、删一条能验出）
"""

from __future__ import annotations

import json

import pytest

from resident_employee.authz import (
    GENESIS,
    AuditChain,
    Grant,
    GrantError,
    canonical_json,
    format_dt,
    in_hours,
    now_utc,
)

from datetime import datetime, timedelta, timezone


def hours_ago(hours: float) -> str:
    return format_dt(datetime.now(timezone.utc) - timedelta(hours=hours))


def make_grant(**overrides) -> Grant:
    base = {
        "issuer": "张三",
        "subject": "key-pool-operator",
        "actions": ("add-alias",),
        "resources": ("api-key-pool",),
        "issued_at": hours_ago(1),
        "expires_at": in_hours(24),
    }
    base.update(overrides)
    return Grant(**base)


# --- 六字段 ----------------------------------------------------------------


def test_complete_grant_validates():
    grant = make_grant()
    assert grant.validate() is grant


@pytest.mark.parametrize("field", ["issuer", "subject"])
def test_missing_text_field_rejected(field):
    with pytest.raises(GrantError, match="缺字段"):
        make_grant(**{field: ""}).validate()


def test_empty_actions_rejected():
    """没给任何权限的授权书不该签——空白名单等于没授权，签了只会误导。"""
    with pytest.raises(GrantError, match="actions 为空"):
        make_grant(actions=()).validate()


def test_empty_resources_rejected():
    with pytest.raises(GrantError, match="resources 为空"):
        make_grant(resources=()).validate()


def test_expiry_must_be_after_issue():
    with pytest.raises(GrantError, match="必须晚于"):
        make_grant(issued_at=in_hours(1), expires_at=in_hours(0)).validate()


def test_max_uses_must_be_positive():
    with pytest.raises(GrantError, match="max_uses 必须"):
        make_grant(max_uses=0).validate()


def test_actions_accept_comma_string():
    grant = make_grant(actions="add-alias, del-alias")
    assert grant.actions == ("add-alias", "del-alias")


# --- 自动生成与不变性 -------------------------------------------------------


def test_ids_are_autogenerated_and_unique():
    a, b = make_grant(), make_grant()
    assert a.grant_id != b.grant_id
    assert a.nonce != b.nonce


def test_grant_is_immutable():
    grant = make_grant()
    with pytest.raises(Exception):
        grant.issuer = "李四"  # type: ignore[misc]


def test_wildcards():
    grant = make_grant(actions=("*",), resources=("*",))
    assert grant.allows_action("任何动作")
    assert grant.allows_resource("任何资源")


def test_signed_payload_excludes_note():
    """note 是给人看的备注，改了不该让签名失效。"""
    a = make_grant()
    b = Grant.from_dict({**a.to_dict(), "note": "改了备注"})
    assert a.signed_payload() == b.signed_payload()


def test_signed_payload_is_canonical():
    """签名基于规范化字节——不同键序必须产出同样的载荷，否则验签会飘。"""
    grant = make_grant()
    payload = json.loads(grant.signed_payload().decode("utf-8"))
    assert canonical_json(payload).encode("utf-8") == grant.signed_payload()


def test_roundtrip_through_dict():
    grant = make_grant()
    assert Grant.from_dict(grant.to_dict()).signed_payload() == grant.signed_payload()


# --- 审计哈希链 -------------------------------------------------------------


@pytest.fixture
def chain(tmp_path) -> AuditChain:
    return AuditChain(tmp_path / "audit.jsonl")


def test_empty_chain_verifies(chain):
    ok, note = chain.verify()
    assert ok
    assert "0 条" in note


def test_append_links_to_previous(chain):
    first = chain.append("issued", grant_id="g-1", actor="张三")
    second = chain.append("allowed", grant_id="g-1", actor="executor")

    assert first.prev_hash == GENESIS
    assert second.prev_hash == first.hash
    assert second.seq == 2
    assert chain.verify()[0]


def test_tampering_is_detected(chain, tmp_path):
    chain.append("issued", grant_id="g-1", actor="张三", detail={"actions": ["add-alias"]})
    chain.append("denied", grant_id="g-1", actor="executor", detail={"decision": "BAD_CODE"})

    path = tmp_path / "audit.jsonl"
    lines = path.read_text(encoding="utf-8").splitlines()
    row = json.loads(lines[0])
    row["detail"]["actions"] = ["del-everything"]  # 事后改权限记录
    lines[0] = canonical_json(row)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    fresh = AuditChain(path)
    ok, note = fresh.verify()
    assert not ok
    assert "被改过" in note


def test_deleting_a_row_is_detected(chain, tmp_path):
    chain.append("issued", grant_id="g-1", actor="张三")
    chain.append("allowed", grant_id="g-1", actor="executor")
    chain.append("revoked", grant_id="g-1", actor="张三")

    path = tmp_path / "audit.jsonl"
    lines = path.read_text(encoding="utf-8").splitlines()
    del lines[1]  # 抽掉中间那条
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    ok, note = AuditChain(path).verify()
    assert not ok
    assert "顺序被改过或记录被删" in note or "前哈希对不上" in note


def test_out_of_order_is_detected(chain, tmp_path):
    chain.append("issued", grant_id="g-1", actor="张三")
    chain.append("allowed", grant_id="g-1", actor="executor")

    path = tmp_path / "audit.jsonl"
    lines = path.read_text(encoding="utf-8").splitlines()
    path.write_text("\n".join(reversed(lines)) + "\n", encoding="utf-8")

    ok, _ = AuditChain(path).verify()
    assert not ok


def test_detail_participates_in_hash(chain, tmp_path):
    """同样的时间/事件，只要 detail 不同，哈希就必须不同。"""
    a = chain.append("denied", detail={"decision": "BAD_CODE"})
    b = chain.append("denied", detail={"decision": "EXPIRED"})
    assert a.hash != b.hash


def test_audit_is_append_only_on_disk(chain, tmp_path):
    """追加不能重写整个文件——审计日志会一直长。"""
    chain.append("issued", grant_id="g-1")
    path = tmp_path / "audit.jsonl"
    first_size = path.stat().st_size
    chain.append("allowed", grant_id="g-1")
    assert path.stat().st_size > first_size
    assert len(path.read_text(encoding="utf-8").splitlines()) == 2
